# -*- coding: utf-8 -*-
"""psFrontend.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gud6fRxdxNTndpd_acZo1Upn2SGaQbTS

# Frontend
## Created using Streamlit for basic algo testing

**Requirements**: install *streamlit* and *requests*
"""

import streamlit as st
import requests

"""Backend"""

BACKEND_URL = "http://localhost:5000/upload"  # Update with your backend URL when hosted

"""File Upload"""

uploaded_file = st.file_uploader(
    "Upload your lecture notes (PDF or DOCX):",
    type=["pdf", "docx"]
)

"""Slider"""

max_pages = st.slider(
    "Maximum number of pages for your cheat sheet:",
    min_value=1,
    max_value=20,
    value=5
)

"""Submission Logic"""

if uploaded_file and st.button("Generate Cheat Sheet"):
    with st.spinner("Processing your request..."):
        try:
            # Send file and max_pages to the backend
            files = {"file": (uploaded_file.name, uploaded_file, uploaded_file.type)}
            data = {"max_pages": max_pages}
            response = requests.post(BACKEND_URL, files=files, data=data)

            if response.status_code == 200:
                # Save and provide download link for the cheat sheet
                cheat_sheet_path = "generated_cheat_sheet.pdf"
                with open(cheat_sheet_path, "wb") as f:
                    f.write(response.content)

                st.success("Cheat sheet generated successfully!")
                st.download_button(
                    label="Download Your Cheat Sheet",
                    data=open(cheat_sheet_path, "rb").read(),
                    file_name="cheat_sheet.pdf",
                    mime="application/pdf"
                )
            else:
                st.error("Failed to generate cheat sheet. Please try again.")
        except Exception as e:
            st.error(f"An error occurred: {e}")